alter table modification 
add column id int(11),
add column description varchar(200),
add column startYear varchar(200),
add column endYear varchar(200),
add column bodyType varchar(200),
add column driveType varchar(200),
add column capacity varchar(200),
add column capacityTax varchar(200),
add column capacityTech varchar(200),
add column fuelMixture varchar(200),
add column fuelType varchar(200),
add column numberOfCylinders varchar(200),
add column numberOfValves varchar(200),
add column constructionInterval varchar(200),
add column engineCode varchar(200),
add column startYearMonth varchar(200),
add column endYearMonth varchar(200);